/**
 * File Storage Service
 * 
 * Manages file system operations for uploaded item images.
 * Handles directory creation, URL generation, and file deletion.
 * 
 * @see specs/002-item-ui-enhancements/data-model.md
 */

const fs = require('fs').promises;
const path = require('path');

const UPLOAD_DIR = path.join(__dirname, '../../data/uploads/items');

/**
 * Ensure upload directory exists
 * 
 * Creates the uploads directory if it doesn't exist.
 * Should be called on application startup.
 * 
 * @returns {Promise<void>}
 */
async function ensureUploadDir() {
  try {
    await fs.mkdir(UPLOAD_DIR, { recursive: true });
    console.log('✓ Upload directory verified:', UPLOAD_DIR);
  } catch (error) {
    if (error.code !== 'EEXIST') {
      console.error('Failed to create upload directory:', error);
      throw error;
    }
  }
}

/**
 * Get relative URL path for uploaded image
 * 
 * Converts a filename to a URL path that can be served by Express static middleware.
 * 
 * @param {string} filename - Filename generated by multer (e.g., "item-1706019234567-abc123def.jpg")
 * @returns {string} Relative URL path (e.g., "/uploads/items/item-1706019234567-abc123def.jpg")
 */
function getImageUrl(filename) {
  return `/uploads/items/${filename}`;
}

/**
 * Delete image file from disk
 * 
 * Removes the physical file from the uploads directory.
 * Handles missing files gracefully (already deleted or never existed).
 * 
 * @param {string} imageUrl - Relative URL path (e.g., "/uploads/items/item-123.jpg")
 * @returns {Promise<void>}
 */
async function deleteImageFile(imageUrl) {
  if (!imageUrl) return;
  
  try {
    const filename = path.basename(imageUrl);
    const filePath = path.join(UPLOAD_DIR, filename);
    await fs.unlink(filePath);
    console.log(`✓ Deleted image file: ${filename}`);
  } catch (error) {
    if (error.code === 'ENOENT') {
      console.warn(`⚠ Image file not found (already deleted): ${imageUrl}`);
    } else {
      console.error(`Failed to delete image file ${imageUrl}:`, error);
      throw error;
    }
  }
}

module.exports = {
  ensureUploadDir,
  getImageUrl,
  deleteImageFile,
  UPLOAD_DIR,
};
